### ISSUE TITLE
Default value as object in props -- not rendered correctly

### ISSUE THREAD

**Issue by bhtw** [HcySunYang/vuese#109]
**Describe the bug**
I experience that if my component has a prop type of object, @vuese cannot render default value properly.

**To Reproduce**
Create a component like this:
```javascript
export default {
  name: "MyComponent",
  props: {
      info: {
          type: Object,
          default() {
            id: "",
            first: "",
            second: ""     
          }
      }
  }
} 
```

**Expected behaviour**
I would expect that this object was inside the "default" value in the props documentation table.

**Actual behaviour**
New lines in Props table are created and mess up the whole props description.

As a workaround I had to add a comment as text above the `default()` object.

```javascript
export default {
  name: "MyComponent",
  props: {
      // Prop holding info object
      info: {
          type: Object,
          // Default values are an object
          default() {
            id: "",
            first: "",
            second: ""     
          }
      }
  }
} 
```

I hope this can be fixed in the future.

**Comment by HcySunYang** [comment]
Close: https://github.com/vue-contrib/vuese/pull/106

**Comment by HcySunYang** [comment]
- @vuese/cli@2.8.1
 - @vuese/markdown-render@2.5.1
 - @vuese/parser@2.4.1
