### ISSUE TITLE
Props默认值为字符串时解析为-

### ISSUE THREAD

**Issue by yalichen19** [HcySunYang/vuese#113]
**Describe the bug**
官方文档上的例子，Props的default没有识别出来，解析为-
```
props: {
  // The name of the form
  name: {
    // `'TOP'` / `'BOTTOM'`
    type: String,
    required: true,
    default: 'TOP'
  }
}

```
**Expected behavior**
default应该是'TOP'

**Screenshots**
官网截图

![屏幕快照 2019-10-09 下午3 01 47](https://user-images.githubusercontent.com/29122467/66460120-de825700-eaa8-11e9-818f-a00807f416a7.png)

**Comment by HcySunYang** [comment]
- @vuese/cli@2.8.2
 - @vuese/markdown-render@2.5.2
 - @vuese/parser@2.4.2
