### ISSUE TITLE
props中type为Boolean时不输出默认值

### ISSUE THREAD

**Issue by Estelle00** [HcySunYang/vuese#115]
![image](https://user-images.githubusercontent.com/5432828/67062040-c095b000-f194-11e9-81ed-538004c408e2.png)
无输出
![image](https://user-images.githubusercontent.com/5432828/67062057-cee3cc00-f194-11e9-828c-866674e74b01.png)

**Comment by HcySunYang** [comment]
如果 `default: true` 是会输出的吧？貌似是在判断真假的时候误把 `false` 作为没有默认值处理了

**Comment by Estelle00** [comment]
还是没有输出

**Comment by HcySunYang** [comment]
可以暂时使用注解解决一下：
```js
{
    // false
    defalut: false
}
```

**Comment by IWANABETHATGUY** [comment]
will be fixed by #150
