### ISSUE TITLE
Question/Docs

### ISSUE THREAD

**Issue by riksnelders** [HcySunYang/vuese#125]
Missing computed documentation? Especially for the vuex mapgetters (and even mutations and actions).

Ive seen some issues concerning this. But is there anyway to properly pick up these mapped instances of vuex ?

**Comment by Viggo95** [comment]
@riksnelders 

The default analysis result does not have  `computed`
For a component that is exposed to other user to import it,  computed are not necessary, props are the most important

- Here you can know the default analysis result ： https://vuese.org/parser/#parserresult
- And If you really need computed options , you can actually add your own personalization ParserOptions
look here: https://vuese.org/parser/#parseroptions

<br>

I personally recommend implementing it yourself by the parseroptions attribute.

**Comment by Viggo95** [comment]
Closing this since I don't think this capability will be supported in the short term. But feel free to reopen.
