### ISSUE TITLE
Authors not feeling enough appreciation for their work.

### ISSUE THREAD

**Issue by adjenks** [HcySunYang/vuese#131]
# 🎉
Great project!
This is really useful and will be more useful as you keep improving it.
Keep up the good work.
Addendum: If you are one of the authors, and you now feel more appreciated, you may close this ticket.

**Comment by QuinnBast** [comment]
While this is good feedback, it probably shouldn't be an issue

**Comment by adjenks** [comment]
You think I don't know that this is improper use of a ticket? Ha.

**Comment by adjenks** [comment]
Wait. Let me fix it for you.
