### ISSUE TITLE
Vuese documentation doest consider description or watch, it only take prop, methods and events

### ISSUE THREAD

**Issue by jmoidunny** [HcySunYang/vuese#134]
**Describe the bug**
Vuese documentation doest consider description or watch, it only take prop, methods and events

**Expected behavior**
It should take component description, component group and watch and computed 
**Screenshots**
![image](https://user-images.githubusercontent.com/54404027/77311122-71c9e480-6cf7-11ea-92b2-9824434dedab.png)
![image](https://user-images.githubusercontent.com/54404027/77311192-96be5780-6cf7-11ea-8919-248aedaa647e.png)

**Environmental information:**
"vuese": "^1.4.7",

**Comment by Quasarman** [comment]
Yeah pretty useless to use this, if you have a component lets say that dosent have any methods, props, events vuese will not create any markdown at all...

**Comment by Viggo95** [comment]
@jmoidunny   
can u update version  to 2.x from ^1.4.7 . And 2.x is fully compatible with 1.x

#### 1.description
Paste the following code [on this page](https://vuese.github.io/vuese-explorer/), you can see the corresponding description
``` JS
<template>
  <div></div>
</template>

<script>
// @vuese
// This component used to create new users
// @group Admin
export default {
  name: 'AdminUserAdd',
  data() {
    return {
      user: {},
      dialog: false,
      errors: {
        email: null,
        password: null
      }
    }
  },
}
</script>
```

![image](https://user-images.githubusercontent.com/22092110/99881024-1a975d80-2c52-11eb-9e59-9bd078a953d8.png)


<br>

#### 2. 「watch」and 「computed」
The default analysis result does not have `watch` and `computed`
For a component that is exposed to other user to import it, `watch` and `computed` are not necessary, `props` are the most important

<br>

- Here you can know the default analysis result ： https://vuese.org/parser/#parserresult
- And If you really need `watch` and `computed` options , **you can actually add your own personalization ParserOptions**
  - look here: https://vuese.org/parser/#parseroptions

<br>
<br>

**Comment by Viggo95** [comment]
> Yeah pretty useless to use this, if you have a component lets say that dosent have any methods, props, events vuese will not create any markdown at all...


Hi  @Quasarman, Generally, No tool can fully meet our needs, but we can optimize it together

**Comment by Quasarman** [comment]
Hello @screetBloom,

I don't really know why I wrote this mean comment at that time (maybe I was frustrated).....I am sorry about that. Actually after reading the documentation it basically already states what can be done in order to generate documentation for components that dont have any props. methods, events, whatsoever. After considering all of this it works like a charm! Thank you!

Kinnd regards.
