### ISSUE TITLE
.sync event are generated in documentation

### ISSUE THREAD

**Issue by devcashsrl** [HcySunYang/vuese#135]
**Describe the bug**
@vuese/cli documentation in "Writing documentation for your component -> events -> .sync event" explain that events named "upadate:xxx" will not be included in the generated documentation, but is not so.

**Expected behavior**
I expect that the these type of events will not be included in the generated documentation.

**Environmental information:**
vuese v2.8.3.

**Comment by IWANABETHATGUY** [comment]
Duplicate of #116

**Comment by IWANABETHATGUY** [comment]
will fix by #144
