### ISSUE TITLE
the browser produced an error that failed to load README.md

### ISSUE THREAD

**Issue by Constaline** [HcySunYang/vuese#136]
**Describe the bug**
After calling `vuese gen` , the browser produced an error that failed to load `README.md`

**To Reproduce**
1.Install vuese
2.Call `vuese gen` at project folder.
3.Open the document folder and there is not  `README.md` in the folder

**Environmental information:**
```
vuese: 2.8.3
```
```
  System:
    OS: Windows 7 6.1.7601
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
  Binaries:
    Node: 8.11.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 5.6.0 - C:\Program Files\nodejs\npm.CMD
```

**Comment by Constaline** [comment]
Maybe it is not a bug.  Copying `README.md` to the document folder can solve this problem.

**Comment by Constaline** [comment]
Is possible to copy `README.md` from root directory to the document folder after generating document?

**Comment by lb091188** [comment]
maybe the `README.md` files is used to write the document content ,not project content.

but the auth doesn`t say

**Comment by IWANABETHATGUY** [comment]
Could you create a repo, so that i can reproduce this

**Comment by Constaline** [comment]
https://github.com/Constaline/vuese-example

The 'docs' folder includes documents. Put 'docs' folder in nginx and access the 'index.html', the browser failed to load '/README.md'

![20200611093446](https://user-images.githubusercontent.com/10860808/84335232-ffb2be80-abc6-11ea-9385-f069eaa9e44a.png)

**Comment by IWANABETHATGUY** [comment]
it's not a bug releated to vuese, i found that the initiator of the request `README.md` is  `docute`
