### ISSUE TITLE
Is there any way to separate .md file in same components directory? 

### ISSUE THREAD

**Issue by JunjaK** [HcySunYang/vuese#137]
User config - markdownFile in vuese-cli Document, There is an example use 'markdownFile' tag.
It is good to use, but I want to convert different component to different markdown file in the same directory.
when I run code `vuese gen --genType='markdown' --markdownDir='*' --markdownFile=''`,
and If there are different components in same directory, It overwrite previous markdown file. So only one markdown is created.

Do you have any idea to solve this problem???

**Comment by adjenks** [comment]
If you mention his other project issues, he might pay attention to this one...
Like so: https://github.com/shuidi-fed/vapper/issues/21
Sorry HcySunYang...

**Comment by IWANABETHATGUY** [comment]
Could please make a specific example, like #156 , so that i could reproduce your question.

**Comment by JunjaK** [comment]
sry. I 'll reproduce this issue someday..
