### ISSUE TITLE
main field in package.json error

### ISSUE THREAD

**Issue by 8zf** [HcySunYang/vuese#171]
In my project folder 'node_modules/@vuese/parser', I found the entry file declared in main field ('dist/lib/index.js')**not match** the actual file ('dist/index.js'), while a bugfix pr has been merged, I'd like to know when the package will be updated, since it's making our private service not working, we have to downgrade this package version now.

Thanks.

**Comment by IWANABETHATGUY** [comment]
I'm sorry about that, i will publish as soon as possible

**Comment by IWANABETHATGUY** [comment]
using latest version would fix
