### ISSUE TITLE
class-component @PropSync decorator not properly documented

### ISSUE THREAD

**Issue by AmberByte** [HcySunYang/vuese#183]
**Describe the bug**
`PropSync` decorators of class components are not correctly documented

**To Reproduce**
Steps to reproduce the behaviour:
1. Component:

```
<script lang="ts">
import Vue from 'vue'
import Component from 'vue-class-component'
import { PropSync } from 'vue-property-decorator'

@Component({
  // ...
})
export default class Child extends Vue {
  @PropSync('foo', { type: String }) fooSync: any
}
</script>
```
2. `vuese gen`
3. Synced Prop *foo* is missing in a generated markdown file

**Expected behaviour**
Prop defined by using `@PropSync` decorator should be documented correctly

**Environmental information:**
Environment Info:

  System:
    OS: Linux 4.19 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 12.18.1 - /usr/bin/node
    npm: 6.14.5 - /usr/bin/npm

**Additional information**
none

**Comment by IWANABETHATGUY** [comment]
fixed by  https://github.com/vuese/vuese/pull/191

**Comment by IWANABETHATGUY** [comment]
closed due  to the new version has been released, fell free to reopen if you have any question
