### ISSUE TITLE
Rename fails due to parsing issue?

### ISSUE THREAD

**Issue by adjenks** [HcySunYang/vuese#192]
**Describe the bug**
File doesn't get renamed to component name.
File is name something like 

**To Reproduce**
1. Have file named `SomethingLikeThis.vue` but with name field: `something-like-this`
2. Have a method containing this:

```js
		sendFile(file){
			var fileObject = {
				_vid: Math.random().toString(),
				name: file.name,
				type: file.type,
				size: file.size,
				progress: {
					loaded: 0,
					total: file.size
				},
				errOpen: false
			}
		}
```
3. File gets saved as `SomethingLikeThis.md` instead of `something-like-this.md`. Whereas all other components get renamed to the kebab case.

**Expected behavior**
File gets renamed to kebab case.

**Environmental information:**

Environment Info:
  System:
    OS: Linux 3.10 CentOS Linux 7 (Core)
  Binaries:
    Node: 12.18.0 - ~/.n/bin/node
    npm: 6.14.4 - ~/.n/bin/npm

**Additional information**
The offending line is `name: file.name,`

rewriting it like so fixes it:

```js 
		sendFile(file){
			var fileObject = {
				_vid: Math.random().toString(),
				type: file.type,
				size: file.size,
				progress: {
					loaded: 0,
					total: file.size
				},
				errOpen: false
			}
			fileObject.name = file['name']
		}
```

After rewriting it, the file is renamed to kebab case like all the other files.

**Comment by adjenks** [comment]
There's more to the function but it's chopped off cause it's not relevant.

I isolated it down to this simple test case:

```js
export default {
	name: 'a-test',
	methods: {
		testmethod(event) {
			var test = {
				name: event.name
			}
		},
	}
}
```

Just add that `testmethod()` as a method and the md files will not get renamed to their name. E.g. `ATest.md` will not get renamed to `a-test.md`.

**Comment by Viggo95** [comment]
@adjenks   What is the version of @vuese/cli

can  use `vuese -v`

<br>

You can upgrade @vuese/cli to version 2.14, I have tested it with `vuese gen` and **it matches the kebab case**

``` js
export default {
	name: 'a-test',
	methods: {
		testmethod(event) {
			var test = {
				name: event.name
			}
		},
	}
}
```
![image](https://user-images.githubusercontent.com/22092110/100628941-b6684e00-3363-11eb-9052-b0ad2ef25d11.png)

**Comment by Viggo95** [comment]
Closing this since I think i've answered the question, but feel free to  reopen.
