### ISSUE TITLE
VUESE and VUEPRESS

### ISSUE THREAD

**Issue by henriquegmatos** [HcySunYang/vuese#199]
Hello,

I met the VUESE component yesterday. I'm picking up here for him to document the components of my project as automatically as possible. I would like to use the Markdown generated by VUESE with VuePress. Apparently the generation of the markdowns worked automatically just using the command "vuese gen". However, vuese generates a menu in an index.html file. Is it possible that he manages a menu in the README.md format to be understood by Vuepress?

I am also not sure if this is the best way. However my goal is to document my entire project automatically and in the end have Vuepress as the documentation frontend. I understood that VuePresse does not have the ability to generate this complete documentation by itself, I also understood that Vuese can help me in this mission.

If my understanding is really correct, what should the process be like to achieve this goal?

congratulations on your component and thanks.

**Comment by IWANABETHATGUY** [comment]
https://buptsteve.github.io/vuepress-plugin-demo-code/#features
maybe this is what you want...

**Comment by ChristianKienle** [comment]
Or [this](https://christiankienle.github.io/cdk/misc/vuepress-plugins/#api-documentation-plugin). I am the author of that VuePress plugin - I am using it for several months… Checkout the [documentation of my corresponding project](https://christiankienle.github.io/cdk/api/) that makes use of that plugin.

**Comment by henriquegmatos** [comment]
thanks Christian
