### ISSUE TITLE
Can't run generation of documentation

### ISSUE THREAD

**Issue by ismatech** [HcySunYang/vuese#221]
I can't run vuese document generation command. It says: "'vuese' is not recognized as an internal or external command,
operable program or batch file." Although I used command from official @vuese/cli site: "yarn global add @vuese/cli". 
Installation was successful.

1. yarn global add @vuese/cli
2. vuese gen

**Expected behavior**
I want to generate documentation for my vue files as website

**Screenshots**

**Environmental information:**
I use Vue 2. Yarn v. 1.22.10. Node v. 14.15.1. Npm v. 6.14.10

**Comment by Viggo95** [comment]
@ismatech  


- Please provide the version of @vuese/cli
- Better give me a screenshot

you can enter the following command in terminal
``` js
vuese -v
```

<br>
<br>

#### Solve this problem
After my testing, it works fine in version 2.14.x, so you can fix it like this
- Install the latest version of @vuese/cli
- Make sure the version is 2.14.x

``` js
yarn global remove @vuese/cli

yarn global add @vuese/cli
```

**Comment by ismatech** [comment]
It's still can't be recognized...
![изображение](https://user-images.githubusercontent.com/30582837/108475248-81ec9a00-72a1-11eb-833c-74134e377581.png)

**Comment by IWANABETHATGUY** [comment]
It seems that  your vuese binary is installed , but not recognized in this terminal session, try to reload the terminal, and also try intall the vuese-cli local without global, then use `npx vuese`

**Comment by ismatech** [comment]
> 
> 
> It seems that your vuese binary is installed , but not recognized in this terminal session, try to reload the terminal, and also try intall the vuese-cli local without global, then use `npx vuese`

Thanks. I'll try. But yesterday I thought the same and even restarted my laptop and nothing changed.

**Comment by ismatech** [comment]
> 
> 
> It seems that your vuese binary is installed , but not recognized in this terminal session, try to reload the terminal, and also try intall the vuese-cli local without global, then use `npx vuese`

Thank you very much for your solution! Command works with npx syntax independently global package or not. But with local installation it works much faster.

Issue is solved.

**Comment by IWANABETHATGUY** [comment]
Ok, i am gonna close this , feel free to open another issue if you have any question
