### ISSUE TITLE
404 error when outDir is used with different path

### ISSUE THREAD

**Issue by janiskelemen** [HcySunYang/vuese#31]
**Describe the bug**
When you use a different output folder via Outdir="/some/folder/path" then it will not find the html file when you try to open the docs. It just shows 404 The requested Path could not be found.

**To Reproduce**
1. vuese gen outDir='resources/docs/1.0/vuese'
2. vuese serve --open

**Expected behavior**
Open the documentation 

**Which version do you use:**
1.4.7

**Comment by HcySunYang** [comment]
Quick solution: use configuration file instead of command line.
```js
// vuese.config.js
module.export = {
    outDir: 'some/folder/path'
}
```

**Comment by HcySunYang** [comment]
Or `vuese serve --open --outDir="resources/docs/1.0/vuese"`

**Comment by HcySunYang** [comment]
I think this is not a bug 😄.

**Comment by andriimanundin27** [comment]
`vuese gen --outDir="public/general/docs" --markdownDir="comp"`
i find html file, but when
`vuese serve --open --outDir="public/general/docs"`
it just shows error: `Unknown option --outDir`

**Comment by QuinnBast** [comment]
I'm getting the same error as @andriimanundin27. You cannot use the `--outDir` flag when using `vuese serve`, You get the error `Unknown option --outDir`

Steps to reproduce:
1. `vuese gen --outDir="something/not/default"`
2. `vuese serve --open` -- produces a 404 not found
3. `vuese serve --open --outDir` -- produces a 404 not found

**Comment by HcySunYang** [comment]
@janiskelemen @HcySunYang 
I made a patch, please use: `@vuese/cli@2.5.2`

**Comment by Alligatore3** [comment]
> I think this is not a bug.

I don't think so :smile: 

this is my **vuese.config**:
```
module.exports = {
  /**
   * @description Output directory of the docute document.
   * {@link https://vuese.org/cli/#outdir}
   */
  outDir: 'documentation',
  include: ['./components/**/*.vue', './pages/**/*.vue'],
  genType: 'docute',
  title: 'Performer'
}
```

And this is my script:
```
  "scripts": {
    "dev": "nuxt",
    "doc": "vuese gen && vuese serve --open --outDir=\"documentation\"",
...
```

Finally I'm using:
```
npm list -g | grep vuese

├─┬ @vuese/cli@2.8.3
│ ├── @vuese/markdown-render@2.5.3
│ ├─┬ @vuese/parser@2.4.3
```

I've also tried with and without option **--outDir** in my script but nothing change.
Thanks.
