### ISSUE TITLE
export default {...} vs const Something = {...}, export { Something }

### ISSUE THREAD

**Issue by GastroGeek** [HcySunYang/vuese#33]
**Describe the bug**
```js
export default {
 // this works OK?
}
```

```js
const MyThing = {
 // this does not work OK
 // only slots is generated?
}

export default MyThing
```

**To Reproduce**
Use the cli tool to parse a single component 'IButton.vue' => 'IButton.md'. Nothing especially fancy. Component content is:

```html
<template>
  <div class="inline-block button" :class="classList">
    <slot name="content"/>
  </div>
</template>
```

```js
<script>
const classMap = {
  sm: 'px-5 py-3 bg-blue text-white hover:bg-red',
  md: 'px-5 py-3 bg-red text-white hover:bg-red',
  lg: 'px-5 py-3 bg-green text-white hover:bg-red'
}

const IButton = {
  name: 'IButton',
  props: {
    // The color of the button
    color: {
      type: String,
      default: 'blue'
    },
    size: {
      type: String,
      default: 'md',
      validator: value => ['sm', 'md', 'lg'].includes(value)
    }
  },
  computed: {
    classList() {
      return classMap[this.size]
    }
  }
}

export { IButton }
export default IButton
</script>
```

**Expected behavior**
It should still work and generate all props, slots etc info

**Which version do you use:**
"@vuese/cli": "^2.0.1"

**Comment by HcySunYang** [comment]
This is because `vuese` only treats `export default {}` as a component. But I don't understand why you use named export?

**Comment by GastroGeek** [comment]
OK, here goes...

Personal taste? consistent conventions? multiple exports? Refactoring large codebases where you may temporarily have said multiple exports from an SFC? the man himself added it to vue-loader (so again, consistency in the broader sense)? Tree shaking in certain scenarios? Because I am adding **please** to the request?

<https://github.com/vuejs/vue-loader/releases/tag/v13.6.0>

But seriously, this tool is great so thank you for making it regardless of your decision to allow named exports.

PS - Please allow named exports 👍

**Comment by HcySunYang** [comment]
Thanks for your information, I will seriously consider it.

**Comment by IWANABETHATGUY** [comment]
test should pass  https://github.com/vuejs/vue-loader/issues/1080

**Comment by IWANABETHATGUY** [comment]
will be finished by #159

**Comment by IWANABETHATGUY** [comment]
will be released next version, if you have any question you could reopen it
