### ISSUE TITLE
How to set componentDesc ? 

### ISSUE THREAD

**Issue by HannibalKcc** [HcySunYang/vuese#36]
**Describe the bug**
How to set componentDesc ? 

**To Reproduce**
https://vuese.github.io/vuese-explorer/ 

**Expected behavior**
i can set componentDesc

**Which version do you use:**
index.js/2.0.1 win32-x64 node-v8.9.3

**Comment by HcySunYang** [comment]
![image](https://user-images.githubusercontent.com/14146560/51664271-0f425f00-1ff4-11e9-9930-fc14c1e1a4a3.png)
