### ISSUE TITLE
TypeScript 2351: Cannot use 'new' with an expression whose type lacks a call or construct signature.

### ISSUE THREAD

**Issue by BuptStEve** [HcySunYang/vuese#38]
**Describe the bug**

TypeScript 2351: Cannot use 'new' with an expression whose type lacks a call or construct signature.
[ts] 其类型缺少调用或构造签名的表达式无法使用 "new"。 [2351]

**To Reproduce**
1. `const VueseRender = require('@vuese/markdown-render')`
2. `const vueseRender = new VueseRender(parserRes, renderOptions)`

**Expected behavior**

no error

**Screenshots**

![image](https://user-images.githubusercontent.com/11501493/51993292-82af0980-24e9-11e9-98e0-1e0f686751c9.png)

**Which version do you use:**
@vuese/markdown-render 2.02

**Additional information**

maybe use `export = class Render {...`?

https://www.typescriptlang.org/docs/handbook/modules.html

**Comment by HcySunYang** [comment]
Why not `import VueseRender from '@vuese/markdown-render'`?

**Comment by BuptStEve** [comment]
You are right, but when you use `commonJs`...

**Comment by BuptStEve** [comment]
How about `export class Render {`? Just like `@vuese/parser`?

https://github.com/vuese/vuese/blob/abdcd052dcb89ba0ca02817d444abf7a647ad494/packages/parser/lib/index.ts#L84
