### ISSUE TITLE
When the component has several methods, the generation seems to have bug.

### ISSUE THREAD

**Issue by gymmer** [HcySunYang/vuese#4]
When the component has more than one `methods`, the generation seems to have bug.

For example:

```
<template>
  <div>
    <!-- Form header -->
    <slot name="header">
      <!-- `<th>title</th>` -->
      <th>title</th>
    </slot>
  </div>
</template>

<script>
export default {
  props: {
    // The name of the form, up to 8 characters
    name: {
      type: [String, Number],
      required: true,
      validator () {}
    }
  },
  methods: {
    // @vuese
    // clear1: Used to manually clear the form
    clear1 () {
      // Fire when the form is cleared
      // @arg The argument is a boolean value representing xxx
      this.$emit('onclear', true)
    },

    // @vuese
    // clear2: Used to manually clear the form
    clear2 () {
      // Fire when the form is cleared
      // @arg The argument is a boolean value representing xxx
      this.$emit('onclear', true)
    }
  }
}
</script>
```

![image](https://user-images.githubusercontent.com/9761363/47425176-2c308180-d7bc-11e8-924e-5d5d70acdde4.png)

**Comment by HcySunYang** [comment]
Just use vuese@1.0.4

**Comment by ferrinweb** [comment]
sorry, but the bug is still exists in 1.0.4 version.
![20181025094416](https://user-images.githubusercontent.com/3353839/47470972-c6cfa580-d83a-11e8-866d-b4bc7e5664e1.png)

**Comment by HcySunYang** [comment]
Can you provide a component that can reproduce the problem? The component you originally provided works fine.

**Comment by ferrinweb** [comment]
Please try this file: [scroll-box.vue](https://github.com/ferrinweb/vue-scroll-box/blob/master/src/lib/scroll-box.vue)
And, this component can reproduce #3 bug, too.

**Comment by HcySunYang** [comment]
Are you sure you installed 1.0.4? I tried it and it works.

**Comment by ferrinweb** [comment]
very sorry, it is indeed that I am wrong, I did not install the new version to the global.
sorry for taking up your time.
