### ISSUE TITLE
生成文档过久，没反应

### ISSUE THREAD

**Issue by MaJiaXuan** [HcySunYang/vuese#43]
**Describe the bug**
运行 vuese gen，等了很久，没反应
![image](https://user-images.githubusercontent.com/24503453/54412722-ca52c300-472e-11e9-857a-4bd519590829.png)

这是配置文件
![image](https://user-images.githubusercontent.com/24503453/54412738-dcccfc80-472e-11e9-87e3-c3c3fdca9c24.png)

**To Reproduce**
1...在项目里运行指令 vuese gen

**Expected behavior**
正常生成文档

**Screenshots**

**Which version do you use:**

**Additional information**
Add any other information about the problem here.

**Comment by HcySunYang** [comment]
You provide very little information, you only say that the command is executed in the project, but what is the structure of the project directory? Which version of `Vuese` are you using?

**Comment by HcySunYang** [comment]
Inactive and closed
