### ISSUE TITLE
The difficulty of static analysis

### ISSUE THREAD

**Issue by HcySunYang** [HcySunYang/vuese#45]
Hello everyone, I've had some difficult problems. `Vuese` uses `@babel/parser` to parse JavaScript into an AST to obtain descriptive information through a specific relationship between the annotation node and the target node, but this relationship can easily be broken:

The following can be handled correctly:

```javascript
// event desc
this.$emit('some-event')
```

The following is not:

```javascript
// event desc
someVar && this.$emit('some-event')
```

I don't think there is any way to cover every case, but we must not limit the user's code, look like the static analysis scenario is not feasible? Are there any other better options?

**Comment by HcySunYang** [comment]
The solution I thought of was to get the correct comment based on the line number. Suppose that the line number of the `$emit()` function call statement is `5`, then try to get the comment content of the fourth line.
So, we need to create an index table like `lineNumber: comments[]` to quickly find the matching comment content.

**Comment by xuzicn** [comment]
It's not possible to gen doc 100% from AST.
I suggest to support some directives to generate a scope to write doc manually. 

/**
 \* @vuese-directive-begin
 \* some-event description
 \* @event some-event
 \* @arg arg description
 \*/
someVar && this.$emit('some-event');
... maybe more code.
/\* @vuese-directive-end \*/

**Comment by IWANABETHATGUY** [comment]
This issue would reopen,  if find other relative scenario
