### ISSUE TITLE
Component with no `props` causes doc gen to halt without error - updated see comment

### ISSUE THREAD

**Issue by roxburghm** [HcySunYang/vuese#46]
### Description

If you have a component with no props, common when using mixins, or an empty props, ie {}, then the gen crashes - using the online vuese explorer reports a "TypeError: Cannot read property 'content' of null" error.

### Reproduce

To reproduce use this very basic template

```
<script>
  export default {
    name: 'BugShowcase',
   }
</script>
```

or this one

```
<script>
  export default {
    name: 'BugShowcase',
	props: {  },
   }
</script>
```

This "fixes" it

```
<script>
  export default {
    name: 'BugShowcase',
	props: {
                fixedIt: { type: Boolean }
	    },
   }
</script>
```

### Expected behavior

Should not crash, and if it does this should be reported when running `vuese gen`.

The documentation should exclude the `props` section if the component has no props or have a props section with "no props"

### Version Info

```
$ npm view vuese version
1.4.7

$ npm view @vuese/cli version
2.1.1
```

### Additional information

This primarily occurs when mixins are used so all properties are abstracted out

**Comment by roxburghm** [comment]
Just stumbled across this - it's not an absence of props because this doesn't break

```
<script>
  export default {
        name: 'BugShowcase',
        methods: {
            // @vuese
            dummymethod() {
                // Do something ...
            },
        }
    }
</script>
```

but this does

```
<script>
  export default {
        name: 'BugShowcase',
        methods: {
            dummymethod() {
                // Do something ...
            },
        }
    }
</script>
```

It's an absence of things to document that seems to be the issue. ie in the case above there are no props and no methods it crashed, ask for the method to be documented and it works.

**Comment by HcySunYang** [comment]
Hello, if `Vuese` does not detect any `props`, `events`, and `methods`(using @vuese) in your component, `Vuese` will not generate documents for it, which is the expected behavior, and I think I should write it clearly on the document.

**Comment by roxburghm** [comment]
Hi, thanks for quick reply, I think it should generate a document, it's a component after all even if it has no methods or properties. The component name and description are as important as methods and properties.

Right now, it doesn't just not generate a document it crashes the gen process and doesn't generate any future documents.

The following is a valid component and Vuese is capable of documenting it
```
<template>
  Some super important markup needed on multiple pages
</template>

<script>
    // Use this component on every page where you want the  super important markup - ad tracking, or logo or anything
    export default {
      name: 'MarkupOnly',
    }
</script>
```
Vuese should document that component as the following

# MarkupOnly

Use this component on every page where you want the  super important markup - ad tracking, or logo or anything

**Comment by roxburghm** [comment]
OK, diving into the code and if I use the markup as follows it will generate the docs - I think that

a. this should be the default behaviour
b. even if it isn't then `vuese gen` should highlight the fact it's been skipped.

```
<script>
  // @vuese
  export default {
        name: 'BugShowcase',
  }
</script>
```

**Comment by HcySunYang** [comment]
@roxburghm 
> a. this should be the default behaviour

If it becomes the default behavior, this will be a breaking change.

> b. even if it isn't then vuese gen should highlight the fact it's been skipped.

Yes, this is an improvement that should be done.

**Comment by HcySunYang** [comment]
I have added the default behavior to the document.
https://vuese.org/cli/#precautions
