### ISSUE TITLE
Feature Request: Mixin Support

### ISSUE THREAD

**Issue by roxburghm** [HcySunYang/vuese#48]
If a component uses mixins then this is not represented in the generated documentation.

### Components

If a component uses a mixin then either

a. they should be listed in a separate table
b. the mixin should be merged into the component and the resultant properties and methods documented (this would be preferable).

For example

```
<script>
export default {
    name: 'FeatureShowcase',
    props: {
         'aprop': { type: Boolean }
    },
    mixins: ['LocationMixIn', 'GeoMixIn']
}
</script>
```

Should Generate

# FeatureShowcase

## Props
|Name|Description|Type|Required|Default|
|---|---|---|---|---|
|aProp|`Boolean`|`false`|-|

## Mixins

|MixIns|
|---|
|LocationMixIn|
|GeoMixIn|

### Mixins

When documenting mixins it's helpful to also document some of the internals, eg computed properties and data

Being able to explicitly document computed properties using `// @vuese` would help greatly

Being able to document data properties in the same way as props would also help mixin clarity.

For example
```
    export default {
        name: 'FeatureDemo',
        data: () => { 
            return {
                // are you ready        
                isReady: false
            } 
        },
        methods: {
            // @vuese
            confirmedAtLocation() {
                // Do something ...
            },
            // @vuese
            cancelledAtLocation() {
                // Do something ...
            },
        },
        computed: {
            // @vuese
            distanceToLocation() {
                // Do something ...
            }
        }
    }
```

Should generate

# FeatureDemo

## Methods

|Method|Description|Parameters|
|---|---|---|
|confirmedAtLocation||-|
|cancelledAtLocation||-|
|distanceToLocation||-|

¢ Internal Fields

## _Data_

|Name|Description|Type|Default|
|---|---|---|---|
|isReady|Are you ready?|Boolean|False|

## _Computed_

|Method|Description|
|---|---|
|distanceToLocation||

Thank you

**Comment by HcySunYang** [comment]
Thanks, I realized the value of it.

**Comment by roxburghm** [comment]
Added a pull request which implements the "Mix Ins" table listing part of this.

**Comment by HcySunYang** [comment]
Thanks to https://github.com/vuese/vuese/pull/51
