### ISSUE TITLE
Line-height is expected to be bigger so that tags will not overlap in vertical direction

### ISSUE THREAD

**Issue by gymmer** [HcySunYang/vuese#5]
I am so sorry to say that the style of generation is sometimes unfriendly. For example, `line-height` is expected to be bigger so that tags will not overlap in vertical direction

![image](https://user-images.githubusercontent.com/9761363/47425513-24bda800-d7bd-11e8-8534-dbe4c70d0271.png)

**Comment by HcySunYang** [comment]
This may be a problem with docute 😟

**Comment by HcySunYang** [comment]
Close inactive
