### ISSUE TITLE
Missing whitespace between first line and summary

### ISSUE THREAD

**Issue by sobolevn** [HcySunYang/vuese#54]
**Describe the bug**
Rendered component documentation misses a whitespace between first line and further description.

**To Reproduce**

Create a `vue` component like so:

```vue
<script lang="ts">
import Vue from 'vue'
import Component from 'nuxt-class-component'
import { Action } from 'vuex-class'

import { CommentType } from '~/types'

// @vue/component
@Component({})
/**
 * Example of the functional Vue component.
 * 
 * By 'functional' we mean that this component does not have any
 * attached state. And only represents behaviour.
 */
export default class ActionBar extends Vue {
  @Action('fetchComments')
  /**
   * Typed alias to Vuex `fetchComments` action.
   */
  fetchComments!: () => Promise<CommentType[]>
}
</script>
```

**Expected behavior**

I expect this text to render with a whitespace between "Vue component" and "By 'functional'".

**Screenshots**

<img width="685" alt="Снимок экрана 2019-03-24 в 12 13 31" src="https://user-images.githubusercontent.com/4660275/54877352-4be0da00-4e2e-11e9-85b3-6584fcdd96d8.png">

**Which version do you use:**

- `node --version`: v10.15.3
- `@vuese/cli` version: 2.2.1

**Comment by HcySunYang** [comment]
@sobolevn 
Use `@vuese/cli@2.2.2`
