### ISSUE TITLE
vuex-class support

### ISSUE THREAD

**Issue by sobolevn** [HcySunYang/vuese#55]
I am not sure how this should be working.

I have this component:

```vue
<script lang="ts">
import Vue from 'vue'
import Component from 'nuxt-class-component'
import { Action } from 'vuex-class'

import { CommentType } from '~/types'

// @vue/component
@Component({})
/**
 * Stateless component.
 * The primary idea of this component is to illustrate,
 * how `@Action` decorator works.
 */
export default class ActionBar extends Vue {
  @Action('fetchComments')
  /**
   * Typed alias to Vuex `fetchComments` action.
   */
  fetchComments!: () => Promise<CommentType[]>
}
</script>
```

Which uses `vuex-class` to type actions from `vuex`.

When documentation is generated it defines `fetchComments` as a `Prop`. And I am not sure if it is a correct thing to do. Since `fetchComments` is an `action` from `vuex`. 

<img width="749" alt="Снимок экрана 2019-03-24 в 12 34 29" src="https://user-images.githubusercontent.com/4660275/54877651-6e74f200-4e32-11e9-82c3-df8b199b12d8.png">

What do you think?

**Comment by HcySunYang** [comment]
This bug was caused by https://github.com/vuese/vuese/commit/e76655c10be862c05225f00378afc16a555dc8fc commit, I have fixed it and added a test case. 
Again: `@vuese/cli@2.2.3`
