### ISSUE TITLE
Types are not set correcty

### ISSUE THREAD

**Issue by sobolevn** [HcySunYang/vuese#56]
**Describe the bug**

Types from `@Prop()`s are not recognised properly. 

Type:

```js
export type RawCommentType = {
  id: number;
  body: string;
  email: string;
}

// We add rating only on the client (for demo purposes)
export type CommentType = RawCommentType & {
  rating: number;
}
```
Source: https://github.com/wemake-services/wemake-vue-template/tree/feature-typescript/template/client/types

And component:

```vue
<script lang="ts">
import Vue from 'vue'
import Component from 'nuxt-class-component'
import { Prop } from 'vue-property-decorator'

import { CommentType } from '~/types'

// @vue/component
@Component({})
/**
 * Comment component is used to represent a single user's comment.
 */
export default class Comment extends Vue {
  @Prop()
  /**
   * Passed comment from the parent component.
   */
  comment!: CommentType
}
</script>
```

Source: https://github.com/wemake-services/wemake-vue-template/blob/feature-typescript/template/client/components/Comment.vue#L32

**Expected behavior**

I expect that `CommentType` from annotation will be set as a type of this property.

<img width="729" alt="Снимок экрана 2019-03-24 в 19 02 28" src="https://user-images.githubusercontent.com/4660275/54882147-2b357600-4e68-11e9-9617-9064014a563e.png">

**Which version do you use:** `2.2.3`

**Comment by IWANABETHATGUY** [comment]
will fix by https://github.com/shuidi-fed/vuese/pull/147
