### ISSUE TITLE
Version 2.2.3 stopped to generate some components

### ISSUE THREAD

**Issue by sobolevn** [HcySunYang/vuese#57]
**Describe the bug**

When I run `vuese gen` it only creates one document out of four. 

```
./node_modules/.bin/vuese gen
✨  Successfully created: /Users/sobolev/Documents/github/wemake-vue-template/template/
website/components/Comment.md
⏳  Start generating...
success Done, let the hacking begin!
✨  Generated successfully
```

I have three components here: https://github.com/wemake-services/wemake-vue-template/tree/feature-typescript/template/client/components
And one here: https://github.com/wemake-services/wemake-vue-template/tree/feature-typescript/template/client/pages

But, only `Comment.vue` file is processed. It started to happen only after `2.2.3` release.

**To Reproduce**
1. Use https://github.com/wemake-services/wemake-vue-template/tree/feature-typescript
2. Use `feature-typescript` branch
3. Edit `{{ name }}` to `name` in `package.json` 
4. Install `@vuese/cli`
5. Run `./node_modules/.bin/vuese gen`

**Expected behavior**
I expect that all my `.vue` components will generate a `.md` file.

**Screenshots**
<img width="353" alt="Снимок экрана 2019-03-24 в 19 13 18" src="https://user-images.githubusercontent.com/4660275/54882238-e65e0f00-4e68-11e9-8fd2-2bfae2b57224.png">

**Which version do you use:** `2.2.3`

**Comment by HcySunYang** [comment]
Hi, please read https://vuese.org/cli/#precautions.
And currently does not support `action`、`mutation` etc., because they are not within the interface scope of the component.
