### ISSUE TITLE
Enhancement request - document Computed properties when flagged using // @vuese

### ISSUE THREAD

**Issue by roxburghm** [HcySunYang/vuese#59]
When generating MixIns then computed properties are important to know about.

Also useful when documenting components for internal use.

I have created a pull request with this feature implemented. Compute docs #58

**Comment by pascalgermain** [comment]
Hi guys,

I use TypeScript in my project and since adding computed, the parsing seems to break with message: 

```
/node_modules/@vuese/parser/dist/index.js:468
   .value.properties.filter(n => bt.isObjectMethod(n) || bt.isObjectProperty(n));
                     ^
TypeError: Cannot read property 'filter' of undefined
```
Happens only for some components, couldn't clearly identify the reason.

Thanks!

**Comment by HcySunYang** [comment]
@pascalgermain 
Can you provide a minimum reproduce it? Or you can test your component with [vuese-explorer](https://vuese.github.io/vuese-explorer/) and see what happens.

**Comment by pascalgermain** [comment]
Yes, I could figure it out (and [vuese-explorer](https://vuese.github.io/vuese-explorer/) was very handy), it's when we use mapGetters from Vuex, we have to do it this way, in the Component decorator:

```
@Component({
  computed: {
    ...mapGetters(module, getters),
  },
})
```

Which works perfectly well, but we also do it like this:

```
@Component({
  computed: mapGetters(module, getters),
})
```

And this breaks. No big deal to write them only the first way, but maybe both ways should be handled on Vuese's side?

**Comment by HcySunYang** [comment]
You are right, this is a flaw in `vuese`.

**Comment by roxburghm** [comment]
Pull request to fix this issue - it should skip over the computed if it's not an object definition.

**Comment by pascalgermain** [comment]
Thanks guys!

**Comment by HcySunYang** [comment]
@pascalgermain 
Use `@vuese/cli@2.2.6`.

**Comment by pascalgermain** [comment]
Works perfectly, thanks again.
