### ISSUE TITLE
Props内默认值为function是解析异常

### ISSUE THREAD

**Issue by Estelle00** [HcySunYang/vuese#6]
如图
![image](https://user-images.githubusercontent.com/5432828/47470424-40b25f80-d838-11e8-9ca7-a6f0dbad6a58.png)
期望：
只显示return后的内容

**Comment by ferrinweb** [comment]
@Estelle00 please submit issues in English.

**Comment by HcySunYang** [comment]
@Estelle00 The props definition in the component is incorrect. You should write this:
```js
target: {
  type: Function,
  default: () => window
}
```

**Comment by Estelle00** [comment]
@HcySunYang but I need return this `() => window`, don't `window`.

**Comment by HcySunYang** [comment]
When `type` is `Function`, the `default` value is the default function itself, you don't need to define a function that returns a function.

**Comment by Estelle00** [comment]
@HcySunYang thanks
