### ISSUE TITLE
Support for seperate TypeScript/JavaScript file

### ISSUE THREAD

**Issue by schmulschubiak** [HcySunYang/vuese#61]
**Describe the bug**
In my Vue components  I have seperated the script-part from the template-/style-part via ``<script lang="ts" src="./myComponent.ts"></script>``

So vuese don't recognize these external script and did not generate documentation.

**To Reproduce**
1. create a vue component file ``myComponent.vue``
2. replace ``<script lang="ts"> ... </script>`` with ``<script lang="ts" src="./myComponent.ts"></script>``
3. externalize the script part in a file named ``myComponent.ts``
4. generate documentation

**Expected behavior**
generated documentation, if script part is external

**Which version do you use:**
1.4.7

**Additional information**
It's not a bug, more a feature request.

**Comment by DrMabuse23** [comment]
I have this same Problem for templates we are using 
````
<template src="./cartEntrySeller.html"></template>
````
it would be a nice feature

**Comment by akashkhaitan** [comment]
I am also facing the same issue.
My vue file is having, script and template separate

Here is the example..
I have **xyz.vue**
which has following content
```
<template src="./xyz.html"></template>
<script src="./xyz.js"></script>
<style src="./xyz.less" scoped lang="less"></style>
```


How do i generate documentation for such component. Please help

**Comment by HcySunYang** [comment]
I just released the following version, support src import:
- @vuese/cli@2.8.0
- @vuese/markdown-render@2.5.0
- @vuese/parser@2.4.0
