### ISSUE TITLE
Make hostname and port configurable

### ISSUE THREAD

**Issue by AmberByte** [HcySunYang/vuese#74]
It is not possible yet to configure the hostname and port of the cli's serve command.
However it may be useful in special use cases, like running the development instance in a docker container.

I would suggest something like:
`vuese serve --host 0.0.0.0 --port 1234`

Also a configuration possibility in the config file would be nice:
```
{
  host: '0.0.0.0',
  port: 1234
}
```

**Comment by BEEugene** [comment]
@tobiasbeck, how do you run it with Docker?
I've tried different options including 
`docker run --rm -p 5000:5000 --mount type=bind,src={path},dst=/data -w /data node:14 /bin/bash -c 'npm install -g @vuese/cli;vuese serve --open --host 0.0.0.0'` but it didn't work
