### ISSUE TITLE
Components with slots in old style not generated

### ISSUE THREAD

**Issue by alexander-sharecreators** [HcySunYang/vuese#75]
**Describe the bug**
Components that contain slots in old style(vue <= 2.5.x) are not generated by ```vuese gen```.
These components are missing in the created *.md files list.

**To Reproduce**
Example of code:
```
<template>
  <div>
    <!-- Header slot -->
    <template slot="header"></template>
  </div>
</template>
```

**Which version do you use:**
```"@vuese/cli": "^2.3.1"```

**Additional information**
You can try this example in your tool https://vuese.github.io/vuese-explorer/

**Comment by HcySunYang** [comment]
This is not a bug, you need to understand the difference between `slot` and `slot content`. The code in your component is the `slot content`, not the `slot`. https://vuese.org/cli/#slots
