### ISSUE TITLE
vuese gen ignoring some components 

### ISSUE THREAD

**Issue by 29rayb** [HcySunYang/vuese#79]
**Describe the bug**
`vuese gen` does NOT create docs for all the components. 
For me personally, only 25% of the components docs are generated. 

**To Reproduce**

**Expected behavior**
`vuese gen` should generate docs for all vue components

**Which version do you use:**
vuese/2.4.1 darwin-x64 node-v11.14.0

**Additional information**

**Comment by HcySunYang** [comment]
Please read: https://vuese.org/cli/#precautions
