### ISSUE TITLE
Keep Folder Structure

### ISSUE THREAD

**Issue by rainerCH** [HcySunYang/vuese#80]
Hi,

wondering if there is an option to keep the folder structure of files when exporting to markdown in a new directory:

```
components/
   - forms/
        MyForm.vue
   - nav/
        LeNav.vue
```

resulting in:

```
components/
    - forms/
          MyForm.md
    - nav/
          LeNav.md
```

.. instead of a flat list of Markdown files.
this would be very useful for automated postprocessing in other markdown tools.
Maybe there should be an option to use the "group" annotation for a new folder structure.

What do you think?

Cheers,
Rainer

**Comment by HcySunYang** [comment]
In fact, you can do this easily with [@vuese/parser](https://vuese.org/parser/) and [@vuese/markdown-render](https://vuese.org/markdown-render/).

**Comment by DogeFlow** [comment]
How to integrate all md documents into one while maintaining the structure

**Comment by HcySunYang** [comment]
@LeMeng7 Sorry, can you explain in detail? I didn't get your opinion.

**Comment by DogeFlow** [comment]
I generated the corresponding md document according to the vue file under different folders, as rainerCH described. I want to integrate them into a technical document, like a book, while maintaining a directory relationship.

**Comment by HcySunYang** [comment]
Oh, I understand what you mean.

**Comment by leoclipet** [comment]
> In fact, you can do this easily with [@vuese/parser](https://vuese.org/parser/) and [@vuese/markdown-render](https://vuese.org/markdown-render/).

May we have an example?

**Comment by IWANABETHATGUY** [comment]
Would be completed by #157

**Comment by IWANABETHATGUY** [comment]
Will be released next version, add `-f` or `--keepFolderStructure` flag to keep folder structure

**Comment by rainerCH** [comment]
Cool, thank you!
