### ISSUE TITLE
command not found: vuese

### ISSUE THREAD

**Issue by Draichi** [HcySunYang/vuese#81]
**Describe the bug**
After installing globally using:
```sh
yarn global add @vuese/cli
```
I receive the following error:
```sh
zsh: command not found: vuese
```
I tried to reboot but still not working.

My spec:
- @vuese/cli@2.4.1
- yarn 1.16.0
- Linux 19.04
- Zsh 5.4.2 (x86_64-ubuntu-linux-gnu)
- Node v10.15.3 (NVM)

Project looks good I'd love to use it.

Thanks :smile:

**Comment by HcySunYang** [comment]
It seems that this problem has nothing to do with vuese. 🤔

**Comment by DavidSGrady** [comment]
How is this not related to vuese? I got the exact same error
