### ISSUE TITLE
Multiline comments are trimmed too aggressively

### ISSUE THREAD

**Issue by ChristianKienle** [HcySunYang/vuese#85]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2410%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/vue-contrib/vuese/issues/85)

**Description**
We are currently adopting vuese in our component library. So far it works pretty well – thank you for this wonderful project.

Some of our components are a bit more complex – for those components we have written guides using plain markdown (for example, [our table component comes with such a guide](https://sap.github.io/fundamental-vue/#/example/table)) which explain step by step how this component works. In addition to those guide we also have API documentation generated by using @vuese/parser. Sometimes we also want to include short examples in the API documentation that show how to use the component. Just to avoid developers going back and forth between the guides and API documentation too much. The example below shows such an example:

```js
<script>
// Use this component together wit `fd-table-fixed` and `fd-table` in order to create a table with a fixed column.
// Example:
// ```xml
// <fd-table-fixed-wrapper>
//   <fd-table-fixed>
//     <fd-table />
//   </fd-table-fixed>
// </fd-table-fixed-wrapper>
// ```
export default {
  name: "FdTableFixedWrapper"
};
</script>
```
Our own renderer uses the component description array produces by vuese/parser, joins it using `\n` and then feeds it into our markdown-component that also does syntax highlighting.

Unfortunately every line in the component description array is trimmed which means that the intention of our example code is gone making it hard to read.

<img width="982" alt="Screenshot 2019-07-05 at 15 34 54" src="https://user-images.githubusercontent.com/153225/60725888-76b4f100-9f3a-11e9-8294-36804fe8e59c.png">

**To Reproduce**
- copy the example above and
- paste it into vuese explorer

**Expected behavior**
I expect that multiline comments are not trimmed from both sides.

**Screenshots**
See above

**Which version do you use:**
latest as of this moment

**Additional information**
I suggest either making the trimming lest aggressive (at least for multiline comments) or add the untrimmed comments as an additional property: "rawCommentDescription" or something like that. This way we could simply use that.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $10.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($10.00)
### Submitted pull Requests
- [#94 Support markdown code blocks](https://issuehunt.io/r/vue-contrib/vuese/pull/94)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/vue-contrib/vuese/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by sudomf** [comment]
hey @ChristianKienle. How are you? Hope that well.

I just create a PR that solves the problem :)

**Comment by ChristianKienle** [comment]
@maykefreitas super cool. :D Can't wait for it to get merged. ❤️

**Comment by sudomf** [comment]
@ChristianKienle hope that it help you :)

**Comment by HcySunYang** [comment]
@ChristianKienle 
```
 - @vuese/cli@2.6.0
 - @vuese/markdown-render@2.4.0
 - @vuese/parser@2.3.0
```
