### ISSUE TITLE
Vue.extend support

### ISSUE THREAD

**Issue by rndmerle** [HcySunYang/vuese#91]
**Describe the bug**
`export default Vue.extend({ /* */ })` component declaration is not supported

**To Reproduce**
Create a SFC with such script:
```
export default Vue.extend({
  props: {
    // String to display
    value: String
  }
})
```
Run @vuese/parser on it.
The parser returns `{ componentDesc: { default: [] } }`

**Expected behavior**
Expected to return the parsed prop, like the same component with a classic `export default { /* */ }` would. So:
```
{ 
  componentDesc: { default: [] },
  props: [ { name: 'value', type: 'String', describe: [ 'String to display' ] } ]
}
```

**Which version do you use:**
vuese/parser 2.2.0

**Comment by leoclipet** [comment]
Any news for this one ?

**Comment by amitozdeol** [comment]
Any update on this?

**Comment by adjenks** [comment]
He hasn't really responded to any tickets in months. He's on vacation or something? Ha...

**Comment by IWANABETHATGUY** [comment]
would fix after next release
