### ISSUE TITLE
How to pronounce Vuese

### ISSUE THREAD

**Issue by TayHobbs** [HcySunYang/vuese#93]
How is this project meant to be pronounced? Is it like "vue" and "use" combined? "v-yooz"?

Thank you

**Comment by HcySunYang** [comment]
Haha yeah, it’s pronounced like views(`[ v'ju:z ]`).

**Comment by cody-baker** [comment]
I would like to propose a revision of the pronounciation to be "v-yoo-eez". So it would be like "Vue" and "ease" (i.e. "ease of use") combined. Think about it 🤷‍♂ 

Overall great package though! 👏 👍

**Comment by TayHobbs** [comment]
@HcySunYang Thank you, you have solved a big office argument!
