### ISSUE TITLE
[CLI]: Have a dedicated flag to show up local environment information

### ISSUE THREAD

**Issue by jamesgeorge007** [HcySunYang/vuese#95]
IMO it is good to have a dedicated flag to show up local environment information, `vuese --info`.
`ISSUE-TEMPLATE` can be updated respectively as well.

Let's discuss :loudspeaker:

**Comment by jamesgeorge007** [comment]
cc @HcySunYang

**Comment by HcySunYang** [comment]
Sorry, I didn't get the information you want to express. Can you tell me more?

**Comment by jamesgeorge007** [comment]
Check out [envinfo](https://npmjs.com/package/envinfo)
